name: Python application

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout repository
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    - name: Install dependences
      run: poetry install
      
    - name: Lint
      run: |
        poetry run flake8 --jobs 4 --statistics --show-source tests app
        poetry run pylint --jobs 4 --rcfile=setup.cfg tests app
        poetry run mypy tests app
        poetry run black --skip-string-normalization --check tests app
        
    - name: Test
      run: |
        poetry run pytest -v --asyncio-mode=strict tests
